### ISSUE TITLE
Implantar elastic search

### ISSUE THREAD

**Issue by leonardofl** [radar-parlamentar/implantacao#20]
Que agora é usado para a funcionalidade de filtro de votações.

**Comment by diraol** [comment]
Como assim @leonardofl? A proposta é trocarmos dr sgdb?
Em 18/04/2015 21:13, "Leonardo Leite" <notifications@github.com> escreveu:

**Comment by leonardofl** [comment]
Nao... no elastic search soh vai ser salvo coisas q ajudam a buscar as votações...
Em sistemas atuais jah eh comum o uso combinado de diferentes BDs pra tirar o melhor proveito de cada um...
O Eduardo talvez possa explicar melhor noq o elastic search ajuda nesse caso.

**Comment by eduardohideo** [comment]
a idéia era usar um mecanismo de busca "full-text" para fazer o filtro.
Ai então considerei o uso do Elasticsearch, toda informação que é colocada nele é indexada e os campos de textos são quebrados em tokens para otimizar a busca em tempo real.
Apesar de parecer exagerado, em 3h de desenvolvimento deu para ter resultado dando trabalho só em fazer um "select" do sgbd para extrair os dados e converter em json. Em baixo o link do resultado no kibana que é uma interface para visualizar os dados do elasticsearch. 
http://ec2-52-10-251-45.us-west-2.compute.amazonaws.com:5601/#/discover?_g=()&_a=(columns:!(_source),index:radar_parlamentar,interval:auto,query:'',sort:!(_score,desc))
Como ele usa REST e json é bem simples fazer tanto consulta como a comunicação.

No Postgres, ainda não vi a engine "full-text" deles, é bem provavel que atualmente seja o suficiente para o filtro pq é bem pouca informação, mas pode ser mais complexo implementar as consultas em sql. 

Em geral, como a busca "full-text" pode ter um processamento "pesado", é um pouco complicado colocar a busca direto com os dados da aplicação, a query pode sobrecarregar a CPU ou memória e dar indisponibilidade/instabilidade na aplicação toda. Ai então tem o banco principal para aplicação e o elasticsearch  que faz as pesquisas.

**Comment by leonardofl** [comment]
Eduardo, antes de automatizar a implantação do elastic search via chef (pretendo fazer isso), agradeceria se vc puder documentar aqui https://github.com/radar-parlamentar/radar/blob/master/doc/INSTALL.md como vc fez isso manualmente aí no seu ambiente de desenvolvedor.
Valeu!

**Comment by eduardohideo** [comment]
ok, coloquei la. Falta só automatizar o processo de coletar os dados do banco e salvar no json.

**Comment by leonardofl** [comment]
Como assim? Vc fez o json na mao? Ou c algum script a parte?
Quando for fazer, lembra d pegar os dados do banco do radar em vez d pegar dos xmls das casas... assim c um código só vc faz o json d qlqr casa! ;)

**Comment by eduardohideo** [comment]
fiz o select a mao no banco, peguei o csv do resultado e converti para json.

**Comment by diraol** [comment]
Hum.... legal isso!

Mas... se estamos usando o ElasticSearch, podemos também pensar em jogar o
texto dos projetos de lei e afins para o ES e rodar uma instância do Kibana
para permitir aos usuários "brincar" nesse base hein!
https://www.elastic.co/products/kibana
Já tive experiência com a dupla (Kibana + ES) e achei bem legal, e sei que
evoluiu muito depois do que eu fiz:
http://polignu.org/artigo/twitter-api-elasticsearch-e-kibana-analisando-rede-social


--------------------------------
Diego Rabatone Oliveira
diraol(arroba)diraol(ponto)eng(ponto)br
Identica: (@diraol) http://identi.ca/diraol
Twitter: @diraol

2015-04-20 19:42 GMT-03:00 eduardohideo <notifications@github.com>:

**Comment by leonardofl** [comment]
Ih, não manjo disso, mas acho q o hideo me mostrou umas coisas numa interface web q acho q era o Kibana. Era isso? Se for é fácil mesmo, neh?

Mas antes tem q ver se isso vai vingar: temos q rodar o povoamento do elastic search para todas as casas e testar se o filtro vai ficar legal usando esse mecanismo.

**Comment by leonardofl** [comment]
Já tá rodando em produção, mas falta ajustes na receita: #21.
