### ISSUE TITLE
Iniciar o Elastic Search de forma idempotente

### ISSUE THREAD

**Issue by leonardofl** [radar-parlamentar/implantacao#21]
Quando executamos a receita radar pela primeira vez, o Elastic Search é iniciado corretamente. Mas se executamos novamente a receita, dá pau na hora de iniciar o Elastic Search que já está iniciado. Isso não deve acontecer.

Talvez o ideal seja usar o esquema do init do linux assim como foi feito com o uwsgi.

**Comment by krlsdu** [comment]
[https://github.com/radar-parlamentar/implantacao/blob/master/cookbooks/radar/recipes/default.rb](url)
Tenho suposições sobre este problema, no seguinte trecho 
`service "elasticsearch" do
  start_command "./#{radar_folder}/elasticsearch-1.5.1/bin/elasticsearch -d"
  action :start
end`

Penso que o action correto é  enable para que o chef gerencie reloads e restarts.
Outra possibilidade seria esta opção -d, que põe o serviço em background sendo assim  o controle passa a ser feito pelo SO e não mais pelo chef.

Concordo que seria ideal colocar sobre o init.

**Comment by leonardofl** [comment]
Humm... não sei se nesse caso o Chef teria algum significado para "enable", já que a instalação do elasticsearch foi apenas baixar e descomapctar um zip... e acho q a ideia é que o controle seja do SO, e o Chef interaja com o serviço da mesma forma que a gente interejaria na linha de comando, não? Mas seria bom pesquisar mais sobre o "-d" e até testar pra ver oq acontece sem ele (mas nesse caso tenho medo do prompt travar e a execução do Chef não ser concluída).

**Comment by krlsdu** [comment]
Encontrei este warning na documentção do chef 

Warning

This is an example of something that should NOT be done. Use the service resource to control a service, not the execute resource.

Do something like this:

service 'tomcat' do
  action :start
end

and NOT something like this:

execute 'start-tomcat' do
  command '/etc/init.d/tomcat6 start'
  action :run
end

**Comment by leonardofl** [comment]
Legal, boa! =)
Agora tem q ver como fazer isso com o elastic search...
Na nossa receita isso foi feito pra alguns carinhas (pelo menos para o celery)... mas lembro q fiz isso bem as cegas seguindo umas dicas específicas pro serviço em questão... no caso do Celery foi essa a parada: https://github.com/radar-parlamentar/implantacao/blob/master/cookbooks/radar/templates/default/celeryd.erb

* O Celery é um componente do Django que se integra com servidores de mensageria (rabbit mq).

**Comment by leonardofl** [comment]
Ah, acho q meio q instalamos o Elastic Search "na mão" lá na receita.... talvez fosse o caso de usar um cookbook de terceiros específico pro Elastic Search...

**Comment by leonardofl** [comment]
Ou então pelo menos instalar com .deb, como o Di fez em http://polignu.org/artigo/twitter-api-elasticsearch-e-kibana-analisando-rede-social. Nesse exemplo, o elasticsearch é iniciado mais decentemente com um "sudo service elasticsearch start".

**Comment by leonardofl** [comment]
Ou seja, se instalar com o .deb, talvez dê pra fazer como @krlsdu recomendou:

service 'tomcat' do
action :start
end

**Comment by leonardofl** [comment]
Então, o pau não tava na hora de iniciar o elastic search, mas na hora de descompactar o zip. E embora ainda seja interessante botar o elastic search pra rodar como um serviço do linux, essa issue em si acaba de ser resolvida usando um método de extração mais adequado (só extrai se arquivo não existe): a547db58733c80a38acc044d162513e9cfb33289.

**Comment by leonardofl** [comment]
Obs: com a resolução desta issue, a receita de implantação  voltou a finalizar sua execução com sucesso!
